[package]
name = "lua"
version = "0.2.0"
authors = [ "kevin@sb.org" ]
description = "Lua 5.1 bindings for Rust"
license = "MIT"
readme = "README.md"
build = "build.rs"

[dependencies]

#libc = "0.1.8"
libc = "*"
